### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by AdrianUofT** [moonsdust/spotify#1]
https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L53-L55

If you aren't using these delete them

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L110

Rewrite this part. Full sentences are preferred.

Makes no coherent sense. 

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L132

You already stated you used R so why are you stating it again??

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L137

In particular what?

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L139

???

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L142

Explain your results

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L513

Ok?

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/paper/paper.qmd#L521

I think it should

https://github.com/moonsdust/top-songs/tree/0fc7a317bc3780666cfebea95a019f29c891e7a3/other/sketches

These don't seem to represent your dataset

https://github.com/moonsdust/top-songs/blob/0fc7a317bc3780666cfebea95a019f29c891e7a3/data/raw_data/raw_data.csv

???

https://tellingstorieswithdata.com/23-assessment.html#rubric-6

Good resource I think

**Comment by moonsdust** [comment]
Resolved.
