### ISSUE TITLE
Final Paper Peer Review

### ISSUE THREAD

**Issue by Diana-Guanzhi-Liu** [moonsdust/spotify#2]
General
https://github.com/moonsdust/top-songs/tree/030b537faa137719a2d85b2428497f58a6f6d82f/scripts
- Scripts are very well done!
https://github.com/moonsdust/top-songs/tree/030b537faa137719a2d85b2428497f58a6f6d82f/other/sketches
- Sketches are good but maybe rename them to be more consistent and informative
- ReadMe is great
https://github.com/moonsdust/top-songs/blob/030b537faa137719a2d85b2428497f58a6f6d82f/paper/casual_model.png
- Move this to sketches?

Paper
https://github.com/moonsdust/top-songs/blob/030b537faa137719a2d85b2428497f58a6f6d82f/paper/paper.qmd#L273-L309
- There are two table 3 with the same caption but different numbers. Table 5 and 7 also has the same issue
- Combining table 2 and 3 might be more useful for comparing their summary statistics. Table 4 and 5  as well as 6&7 could also be combined for this purpose

**Comment by moonsdust** [comment]
Resolved
