### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by curvagrande** [moonsdust/spotify#3]
- title and subtitle is well written as it tells the audience what will be done in the paper
- author and date is up to date
- abstract is great as it is easy to know what the goal of the paper is and how the results may effect the audience.
- introduction is also great as it introduces what will be done throughout the paper in detail
- all tables and graphs produced seem good
- all code that has been written in appropriate style.

- the name of the paper could be changed to something more related to the intended study

overall this seems great. hope you keep up the work and finish up the writing part

**Comment by moonsdust** [comment]
Resolved.
