### ISSUE TITLE
Peer Review Round 2

### ISSUE THREAD

**Issue by SachinChhikara** [moonsdust/spotify#5]
Overall: 
- delete the datasheet from the repo 
- put a link to your shiny app in the your README.md

Paper: 

Abstract: Informative and just the right length.

Introduction:
- Who is Ghaffari et al?
- Same with the other people you mention
- Remove the TODO 

Data:
- Remove TODO
- Finish the Variables of Interest section

Model: 
Good job, this section is well done.

Result:
- remove [To finish]
- a lot of graphs in this section , so them can remove
- make sure to complete this section

Discussion:
- section is incomplete, make sure to complete it

Overall, an interesting idea for a paper, the section that are complete look good but make sure to finish up the incomplete sections.

**Comment by moonsdust** [comment]
Resolved
